### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by sandeepuno** [facebookarchive/webscalesql-5.6#17]
I got the following errors during build.
Centos 7
x86_64

```
sql/net_serv.cc:547:29: error: 'len' was not declared in this scope
       MYSQL_NET_WRITE_START(len);
                             ^
```

```
include/probes_mysql_dtrace.h:526:1: error: template argument 1 is invalid
 DTRACE_PROBE1(mysql,net__write__start,arg1)
 ^
```

**Comment by steaphan-fb-com** [comment]
This doesn't look right.  Can you send the full build commands, and full build output, you are using/seeing, along with the exact git revision you are building?

**Comment by sandeepuno** [comment]
Thanks for the response. I tried on fresh install and got the error. These same commands worked on 5.6.22 but fails on 5.6.23 with the following error.

Git Revision: 0829645557af70317eb15309134a5ff5dedf616f
Build Output: https://gist.github.com/sandeepone/e401e4b6a5eccf57d65a

Build Command:

```
cmake   -DBUILD_CONFIG=mysql_release \
        -DENABLE_DOWNLOADS=1 \
        -DWITH_INNODB_MEMCACHED=1 \
        -DMYSQL_TCP_PORT=3337 \
        -DMYSQL_UNIX_ADDR=/tmp/webscalesql.sock \
        -DMYSQL_DATADIR=/opt/webscalesql/data \
        -DSYSCONFDIR=/opt/webscalesql \
        -DWITH_INNOBASE_STORAGE_ENGINE=1 \
        -DDEFAULT_CHARSET=utf8 \
        -DDEFAULT_COLLATION=utf8_general_ci \
        -DFEATURE_SET="community" \
        -DCOMPILATION_COMMENT="WebScaleSQL Server (GPL)" \
        -DCMAKE_INSTALL_PREFIX=/opt/webscalesql/  .

make -j5 || true
```

**Comment by steaphangreene** [comment]
I believe this is fixed by this proposed diff: https://reviews.facebook.net/D33777

**Comment by steaphangreene** [comment]
And, that fix has now been pushed.  Please open a new issue if you find things are still not working.
